---
title: "Estadisticas Policiales 2021"
author: "Jordan Fabricio Monge Obando"
date: '2022-06-18'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Carga de paquetes

```{r}
library(dplyr)
library(DT)
library(readxl)
library(ggplot2)
library(plotly)
library(readr) 
```

# Lectura del documento de estadisticas policiales

```{r}
estadisticas_policiales <-
  read_xls(path = "C:/Users/Jordan/Documents/estadisticaspoliciales2021.xls")
```


# Una tabla DT

```{r}
estadisticas_policiales %>%
  select(Delito, Fecha, Victima, Edad, Genero, Provincia, Canton) %>%
datatable(
  colnames = c("Delito", "Fecha", "Víctima", "Edad", "Género", "Provincia","Cantón."),
  options = list(
  pageLength = 5,
  language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
))
```

# Un grafico de barras simples generado para los tipos de delitos

```{r}
ggplot2_barras_conteo <-
  estadisticas_policiales %>%
  ggplot(aes(x = Delito)) +
  geom_bar() +
  ggtitle("Grafico de delitos por tipo de delito") +
  xlab("Tipo de delito") +
  ylab("Cantidad de delitos") +
  coord_flip()+
  theme_minimal()
ggplotly(ggplot2_barras_conteo) %>% config(locale = 'es')
```


# Barras apiladas según el genero

```{r}
ggplot2_barras_apiladas_proporcion <-
  estadisticas_policiales %>%
  ggplot(aes(x = Delito, fill = Genero)) +
  geom_bar(position = "fill") +
  ggtitle("Tipo de delito en proporción al genero") +
  xlab("Tipo de delito") +
  ylab("Proporción") +
  labs(fill = "Genero") +
  coord_flip()+
  theme_minimal()

ggplotly(ggplot2_barras_apiladas_proporcion) %>% config(locale = 'es')
```
